/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [882.96KB] > scene-transformed.glb [930.28KB] (-5%)
Author: Reyhue (https://sketchfab.com/Reyhue)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/valheim-black-forest-56530ca0304a409e9082830ffabfb077
Title: Valheim Black Forest
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Forest(props) {
  const { nodes, materials } = useGLTF('./models/valheim_black_forest/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Terrain_TerrainMat_0.geometry} material={materials.TerrainMat} rotation={[-Math.PI / 2, 0, 0]} scale={[9.711, 9.711, 7.375]} />
      <mesh geometry={nodes.Tronchi_ElementsMat_0.geometry} material={materials.ElementsMat} position={[3.743, 0.254, 0.372]} rotation={[-Math.PI / 2, 0, -0.309]} scale={0.534} />
      <mesh geometry={nodes.Casa_StrawMat_0.geometry} material={materials.StrawMat} position={[0.277, -0.043, 4.848]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.277, 0.585, 0.409]} />
      <mesh geometry={nodes.Alberi_FoliageMat_0.geometry} material={materials.FoliageMat} position={[6.103, 3.907, 7.269]} rotation={[-1.532, -0.086, 1.336]} scale={[0.522, 0.558, 1.342]} />
      <mesh geometry={nodes.GreyDwarf_GreyDwarf_0.geometry} material={materials.material_0} position={[-7.656, 2, 1.141]} rotation={[-0.952, -1.457, -0.767]} scale={0.942} />
      <mesh geometry={nodes.Fire_Fire_0.geometry} material={materials.Fire} position={[0, 0.765, 0.02]} scale={0.981} />
      <instancedMesh args={[nodes['Terrain|Plane001|Dupli|_GrassMat_0'].geometry, materials.GrassMat, 417]} instanceMatrix={nodes['Terrain|Plane001|Dupli|_GrassMat_0'].instanceMatrix} />
      <instancedMesh args={[nodes.ErbaNew_GrassMat2_0.geometry, materials.GrassMat2, 6]} instanceMatrix={nodes.ErbaNew_GrassMat2_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('./models/valheim_black_forest/scene-transformed.glb')
